version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "80"
      volumes:
          - ./app:/var/app
      environment:
          - VIRTUAL_HOST=staging.drinkglo.com,www.drinkglo.com,drinkglo.com
          - VIRTUAL_PORT=80
      network_mode: "bridge"
      links:
      - fpm
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=lemp"
      network_mode: "bridge"
      links:
      - db
  db:
      image: mariadb
      environment:
          - MYSQL_DATABASE=lemp      
          - MYSQL_ROOT_PASSWORD=changeme
      network_mode: "bridge"
      volumes:
          #- ./database:/var/lib/mysql
          - ./sql:/docker-entrypoint-initdb.d
          - ./sql:/sql
