version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "80"
      volumes:
          - ./app:/var/app
          - ./nginx/default.conf:/etc/nginx/default.conf
      environment:
          - VIRTUAL_HOST=shoes.docker
          - VIRTUAL_PORT=80
      network_mode: "bridge"
      links:
      - fpm
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
          - ./fpm/php.ini:/etc/php/7.0/fpm/php.ini
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=lemp"
      network_mode: "bridge"
      links:
      - db
  db:
      image: mariadb
      environment:
          - MYSQL_DATABASE=lemp
          - MYSQL_ROOT_PASSWORD=changeme
      network_mode: "bridge"
      volumes:
          #- ./database:/var/lib/mysql
          - ./sql:/docker-entrypoint-initdb.d
          - ./sql:/sql
